#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path


PROFILE_LADDER = ["veritas", "votum", "visions", "vorago"]
EDITION_TO_PROFILES = {
    "shared": PROFILE_LADDER,
    "veritas": PROFILE_LADDER,
    "votum": PROFILE_LADDER[1:],
    "visions": PROFILE_LADDER[2:],
    "vorago": PROFILE_LADDER[3:],
}


def parse_array(raw: str):
    return re.findall(r'"([^"]+)"', raw)


def load_existing_manifest(path: Path):
    records = {}
    current = None
    if not path.exists():
        return records

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        section_match = re.match(r'^\[modules\."([^"]+)"\]$', line)
        if section_match:
            current = section_match.group(1)
            records.setdefault(current, {})
            continue

        if current is None:
            continue

        if line.startswith("name = "):
            records[current]["name"] = re.match(r'^name\s*=\s*"([^"]*)"$', line).group(1)
        elif line.startswith("category = "):
            records[current]["category"] = re.match(r'^category\s*=\s*"([^"]*)"$', line).group(1)
        elif line.startswith("tags = "):
            records[current]["tags"] = parse_array(line)

    return records


def derive_name(project_key: str):
    slug = project_key.split(":")[-1]
    return slug.replace("-", " ").title()


def scan_modules(repo_root: Path, existing_records):
    modules = {}
    for metadata_path in sorted(repo_root.glob("modules/**/module.json")):
        module_dir = metadata_path.parent
        if not (module_dir / "build.gradle").exists() and not (module_dir / "build.gradle.kts").exists():
            continue

        project_key = module_dir.relative_to(repo_root).as_posix().replace("/", ":")
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        edition = metadata["edition"]
        if edition not in EDITION_TO_PROFILES:
            raise SystemExit(f"Unsupported edition '{edition}' in {metadata_path}")

        existing = existing_records.get(project_key, {})
        modules[project_key] = {
            "name": existing.get("name", derive_name(project_key)),
            "edition": EDITION_TO_PROFILES[edition],
            "category": existing.get("category", metadata["domain"]),
            "tags": existing.get("tags", [metadata["domain"]]),
        }
    return modules


def format_manifest(modules):
    lines = [
        "# Verbum Module Manifest",
        "# This file is auto-generated by `tools/scripts/update_module_manifest.py` from module.json metadata.",
        "# Do not edit by hand.",
        "",
    ]

    for project_key in sorted(modules):
        record = modules[project_key]
        edition_values = ", ".join(f'"{value}"' for value in record["edition"])
        tag_values = ", ".join(f'"{value}"' for value in record["tags"])
        lines.extend(
            [
                f'[modules."{project_key}"]',
                f'name = "{record["name"]}"',
                f"edition = [{edition_values}]",
                f'category = "{record["category"]}"',
                f"tags = [{tag_values}]",
                "",
            ]
        )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate or verify modules/modules.toml from module.json metadata.")
    parser.add_argument("--check", action="store_true", help="Verify the manifest is up to date")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    manifest_path = repo_root / "modules/modules.toml"
    existing_records = load_existing_manifest(manifest_path)
    modules = scan_modules(repo_root, existing_records)
    output = format_manifest(modules)

    if args.check:
        if not manifest_path.exists():
            raise SystemExit("Missing modules/modules.toml. Run tools/scripts/update_module_manifest.py")
        if manifest_path.read_text(encoding="utf-8") != output:
            raise SystemExit("modules/modules.toml is out of date. Run tools/scripts/update_module_manifest.py")
        return

    manifest_path.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
