#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
index_file="${repo_root}/docs/TODO_INDEX.md"

todos=()
if [[ -d "${repo_root}/modules/features" ]]; then
  while IFS= read -r line; do
    todos+=("$line")
  done < <(cd "${repo_root}" && find modules/features -type f -path "*/docs/TODO.md" | sort)
fi

{
  echo "# TODO Index (Repo Agent)"
  echo
  echo "This file is auto-generated by \`tools/scripts/update_todo_index.sh\`."
  echo "Do not edit by hand."
  echo
  echo "## Root TODO"
  echo "- \`TODO.md\` (repo-level orchestration and wiring tasks)"
  echo
  echo "## Capsule TODOs"
  if [[ ${#todos[@]} -eq 0 ]]; then
    echo "- (none found)"
  else
    for todo in "${todos[@]}"; do
      echo "- \`${todo}\`"
    done
  fi
  echo
  echo "## How to Maintain"
  echo "- Repo agents run \`tools/scripts/update_todo_index.sh\` when a capsule is added or removed."
  echo "- Commit hook (if installed) updates this file automatically."
  echo "- Capsule agents never edit this file."
} > "${index_file}"
